"""Add case_id and is_fraud to withdrawals

Revision ID: 7ae9c074978e
Revises: fcb3665d399c
Create Date: 2026-09-14 21:22:42.671032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae9c074978e'
down_revision: Union[str, Sequence[str], None] = 'fcb3665d399c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('case_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_withdrawals_case_id'), 'withdrawals', ['case_id'], unique=False)
    op.add_column('withdrawals', sa.Column('is_fraud', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'is_fraud')
    op.drop_index(op.f('ix_withdrawals_case_id'), table_name='withdrawals')
    op.drop_column('withdrawals', 'case_id')
    # ### end Alembic commands ###
