"""Add account_id and fraud_amount to Complaint

Revision ID: d085c41719ed
Revises: 7ae9c074978e
Create Date: 2026-09-14 21:24:59.777142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd085c41719ed'
down_revision: Union[str, Sequence[str], None] = '7ae9c074978e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('fraud_amount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_complaints_account_id'), 'complaints', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_account_id'), table_name='complaints')
    op.drop_column('complaints', 'fraud_amount')
    op.drop_column('complaints', 'account_id')
    # ### end Alembic commands ###
