"""Add evidence file fields

Revision ID: fcb3665d399c
Revises: 253699da032c
Create Date: 2026-09-14 12:40:48.039990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb3665d399c'
down_revision: Union[str, Sequence[str], None] = '253699da032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('stored_filename', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'file_size')
    op.drop_column('evidence', 'mime_type')
    op.drop_column('evidence', 'stored_filename')
    op.drop_column('evidence', 'original_filename')
    # ### end Alembic commands ###
